(function(root){
'use strict';
const groups={start:{label:'สตาร์ทไม่ติด',desc:'บิดกุญแจแล้วเงียบ หรือมีเสียงผิดปกติ',icon:'power',causes:['ระบบไฟฟ้า / แบตเตอรี่','ระบบสตาร์ท','ระบบเชื้อเพลิง / เครื่องยนต์']},noise:{label:'เสียงผิดปกติ',desc:'เสียงที่ต่างจากเดิมขณะใช้รถ',icon:'sound',causes:['ล้อ / ช่วงล่าง','ระบบเบรก','เครื่องยนต์ / อุปกรณ์ขับเคลื่อน']},warning:{label:'ไฟเตือนบนหน้าปัด',desc:'มีสัญลักษณ์หรือข้อความแจ้งเตือน',icon:'alert',causes:['ระบบที่ไฟเตือนระบุ','เซนเซอร์ / ระบบไฟฟ้า','เครื่องยนต์ / ระบบที่เกี่ยวข้อง']},vibration:{label:'รถสั่น / การขับเปลี่ยนไป',desc:'พวงมาลัย ตัวรถ หรือรอบเครื่องสั่น',icon:'wave',causes:['ล้อ / ยาง / ช่วงล่าง','เครื่องยนต์ / ระบบส่งกำลัง','ระบบเบรก']}};
const common=[{id:'repeat',text:'อาการนี้เกิดบ่อยแค่ไหน?',hint:'ตอบจากสิ่งที่เคยพบ ไม่ต้องทดลองให้เกิดซ้ำ',S:2,E:5,R:0,options:['ครั้งแรก','เป็นบางครั้ง','เป็นต่อเนื่อง'],weights:[[0,0,0],[0,0,0],[0,0,0]]}];
const questions={
start:[{id:'startsound',text:'ตอนที่สตาร์ทไม่ติด คุณได้ยินเสียงแบบไหน?',hint:'นึกถึงครั้งที่เกิดอาการ ไม่ต้องลองสตาร์ทซ้ำ',S:5,E:5,R:0,options:['เงียบ ไม่มีเสียงหมุน','มีเสียงแชะ ๆ','เครื่องหมุน แต่ไม่ติด'],weights:[[2,2,0],[3,2,0],[0,0,4]]},{id:'lights',text:'ในครั้งนั้น ไฟหน้าปัดมีลักษณะอย่างไร?',hint:'ถ้าจำไม่ได้ เลือก “ไม่ทราบ” ได้',S:4,E:5,R:0,options:['หรี่ลงหรือดับ','สว่างตามปกติ'],weights:[[4,1,0],[0,2,1]]},{id:'recent',text:'ก่อนเกิดอาการ มีข้อมูลใดที่คุณจำได้?',hint:'เลือกสิ่งที่ตรงที่สุดจากประวัติการใช้งาน',S:3,E:5,R:0,options:['จอดไว้นาน / เคยเปิดอุปกรณ์ทิ้งไว้','เพิ่งมีการซ่อมหรือเปลี่ยนอุปกรณ์','ไม่มีเหตุการณ์ที่สังเกตได้'],weights:[[3,0,0],[1,1,1],[0,0,0]]}],
noise:[{id:'whennoise',text:'จากครั้งที่ได้ยิน เสียงเกิดในช่วงใด?',hint:'ไม่ต้องขับทดสอบเพื่อหาคำตอบ',S:5,E:5,R:0,options:['ขณะเบรก','ขณะเลี้ยว / ผ่านพื้นขรุขระ','ขณะเครื่องยนต์ทำงาน'],weights:[[0,4,0],[4,0,0],[0,0,4]]},{id:'noisetype',text:'เสียงที่ได้ยินใกล้เคียงแบบไหน?',hint:'บอกลักษณะคร่าว ๆ ได้ ไม่ต้องระบุตำแหน่งชิ้นส่วน',S:4,E:5,R:0,options:['ครูด / เสียดสี','กึก / กระแทก','หอน / หวีด'],weights:[[1,2,0],[3,0,1],[1,0,2]]},{id:'noiselocation',text:'เสียงดูเหมือนมาจากบริเวณใด?',hint:'ตอบตามที่สังเกตได้จากในรถ',S:3,E:4,R:0,options:['ด้านหน้า','ด้านหลัง','ระบุตำแหน่งไม่ได้'],weights:[[1,1,1],[2,1,0],[0,0,0]]}],
warning:[{id:'warningtype',text:'คุณจำลักษณะไฟหรือข้อความเตือนได้หรือไม่?',hint:'ระบุจากที่เคยเห็น ไม่ต้องเปิดรถเพื่อทดสอบ',S:5,E:5,R:0,options:['รูปเครื่องยนต์','รูปแบตเตอรี่','ข้อความ / สัญลักษณ์อื่น'],weights:[[2,1,3],[3,3,0],[3,1,1]]},{id:'warningtime',text:'ครั้งนั้น ไฟเตือนแสดงช่วงใด?',hint:'ข้อมูลนี้ใช้เล่าอาการให้ช่าง ไม่ใช้รับรองว่ารถปลอดภัย',S:4,E:5,R:0,options:['แสดงต่อเนื่องขณะใช้งาน','ติดแล้วดับ','จำช่วงเวลาไม่ได้'],weights:[[2,1,2],[1,1,0],[0,0,0]]},{id:'warningother',text:'มีอาการอื่นร่วมด้วยที่คุณจำได้ไหม?',hint:'ถ้ามีเหตุที่ไม่ปลอดภัย ใช้ปุ่มหยุดคัดกรองได้เสมอ',S:3,E:5,R:0,options:['เครื่องทำงานต่างจากเดิม','อุปกรณ์ไฟฟ้าผิดปกติ','ไม่สังเกตอาการอื่น'],weights:[[1,0,3],[1,3,0],[0,0,0]]}],
vibration:[{id:'vibwhen',text:'ครั้งที่พบอาการ รถสั่นในช่วงใด?',hint:'ตอบจากประสบการณ์เดิม ไม่ต้องขับทดสอบ',S:5,E:5,R:0,options:['ขณะเบรก','ขณะจอด / เครื่องเดินเบา','ขณะรถเคลื่อนที่'],weights:[[1,0,4],[0,4,0],[3,1,0]]},{id:'vibwhere',text:'คุณรู้สึกถึงการสั่นบริเวณใดมากที่สุด?',hint:'ไม่จำเป็นต้องรู้ชื่อชิ้นส่วน',S:4,E:5,R:0,options:['พวงมาลัย','ตัวรถ / เบาะ','บริเวณเครื่องยนต์'],weights:[[3,0,1],[2,2,0],[0,4,0]]},{id:'vibrecent',text:'ก่อนเกิดอาการ มีเหตุการณ์ใดที่จำได้?',hint:'ข้อมูลประวัติช่วยให้ช่างเลือกจุดตรวจได้',S:3,E:5,R:0,options:['ผ่านหลุม / มีการเปลี่ยนยาง','เพิ่งซ่อมหรือบำรุงรักษา','ไม่มีเหตุการณ์ที่สังเกตได้'],weights:[[3,0,0],[1,1,1],[0,0,0]]}]
};
function all(category){return [...(questions[category]||[]),...common];}
function next(category,answers){return all(category).filter(q=>!answers.some(a=>a.id===q.id)).map(q=>{const first=answers[0];let S=q.S;if(category==='start'&&q.id==='lights'&&first?.answer==='มีเสียงแชะ ๆ')S=5;if(category==='noise'&&q.id==='noiselocation'&&first?.answer==='ขณะเลี้ยว / ผ่านพื้นขรุขระ')S=5;return {...q,S,score:S*q.E/(q.R+1)};}).sort((a,b)=>b.score-a.score)[0]||null;}
function rank(category,answers){const scores=[1,1,1],reasons=[[],[],[]];for(const a of answers){const q=all(category).find(q=>q.id===a.id);const i=q?.options.indexOf(a.answer);if(i===undefined||i<0)continue;q.weights[i].forEach((w,j)=>{scores[j]+=w;if(w>0)reasons[j].push(a.answer);});}return groups[category].causes.map((label,i)=>({label,score:scores[i],reasons:reasons[i]})).sort((a,b)=>b.score-a.score);}
function shouldStop(safety,answers){if(safety==='yes')return 'พบสัญญาณที่ผู้ใช้ระบุว่าอาจไม่ปลอดภัย';if(safety==='unknown')return 'ผู้ใช้ไม่มั่นใจเรื่องความปลอดภัย';if(answers.filter(a=>a.answer==='ไม่ทราบ').length>=2)return 'ข้อมูลยังไม่พอ ควรให้ช่างตรวจต่อ';if(answers.length>=4)return 'รวบรวมข้อมูลเบื้องต้นครบแล้ว';return null;}
function validCase(c){return !!(c&&typeof c.id==='string'&&c.id.length<=100&&groups[c.category]&&typeof c.vehicle==='string'&&c.vehicle.length<=200&&typeof c.created==='string'&&!isNaN(Date.parse(c.created))&&typeof c.reason==='string'&&c.reason.length<=1000&&['yes','no','unknown'].includes(c.safety)&&Array.isArray(c.answers)&&c.answers.length<=10&&c.answers.every(a=>typeof a.id==='string'&&typeof a.question==='string'&&a.question.length<=1000&&typeof a.answer==='string'&&a.answer.length<=1000));}
const api={groups,questions,all,next,rank,shouldStop,validCase};root.Carwise=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
